version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-gs
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  oracle-db:
    image: gvenzl/oracle-free
    container_name: oracle-gs
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=password
      - APP_USER=myuser
      - APP_USER_PASSWORD=password
    volumes:
      - oracle_data:/container-entrypoint-initdb.d

volumes:
  rabbitmq_data:
  oracle_data:
