--======================================================================
-- PROJETO: PATHFINDER AI - SCRIPT FINAL COMPLETO (VERSÃO FINAL)
--======================================================================

SET SERVEROUTPUT ON;
SET DEFINE OFF;

--======================================================================
-- 1. LIMPEZA DE AMBIENTE (DROP TABLE)
--======================================================================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOG_AUDITORIA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ETAPA_SKILL CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ETAPA_TRILHA CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE TRILHA_APRENDIZAGEM CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PERFIL_SKILL CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE SKILL CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE PERFIL CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE USUARIO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL; -- Ignora erro se tabelas não existirem
END;
/

--======================================================================
-- 2. CRIAÇÃO DAS TABELAS (DDL - 3ª FORMA NORMAL)
--======================================================================

CREATE TABLE USUARIO (
    ID_USUARIO      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME            VARCHAR2(100) NOT NULL,
    EMAIL           VARCHAR2(100) NOT NULL UNIQUE,
    SENHA_HASH      VARCHAR2(255) NOT NULL,
    DATA_CRIACAO    DATE DEFAULT SYSDATE
);

CREATE TABLE PERFIL (
    ID_PERFIL               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_USUARIO              NUMBER NOT NULL UNIQUE,
    TITULO_CARGO_ATUAL      VARCHAR2(100),
    DATA_ULTIMA_ATUALIZACAO DATE,
    CONSTRAINT FK_PERFIL_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE SKILL (
    ID_SKILL        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME_SKILL      VARCHAR2(100) NOT NULL UNIQUE,
    TIPO            VARCHAR2(20) NOT NULL CHECK (TIPO IN ('HARD', 'SOFT', 'COMPORTAMENTAL'))
);

CREATE TABLE PERFIL_SKILL (
    ID_PERFIL_SKILL NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_PERFIL       NUMBER NOT NULL,
    ID_SKILL        NUMBER NOT NULL,
    NIVEL_DOMINIO   NUMBER DEFAULT 1 CHECK (NIVEL_DOMINIO BETWEEN 1 AND 5),
    CONSTRAINT FK_PS_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL),
    CONSTRAINT FK_PS_SKILL FOREIGN KEY (ID_SKILL) REFERENCES SKILL(ID_SKILL),
    CONSTRAINT UK_PERFIL_SKILL UNIQUE (ID_PERFIL, ID_SKILL)
);

CREATE TABLE TRILHA_APRENDIZAGEM (
    ID_TRILHA               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_PERFIL               NUMBER NOT NULL,
    TITULO_OBJETIVO         VARCHAR2(100) NOT NULL,
    DATA_GERACAO            DATE DEFAULT SYSDATE,
    STATUS                  VARCHAR2(20) DEFAULT 'PENDENTE' CHECK (STATUS IN ('PENDENTE', 'EM_PROGRESSO', 'CONCLUIDA', 'GERADA', 'ERRO')),
    DADOS_JSON_IA           CLOB, -- Campo para armazenar o JSON da IA
    CONSTRAINT FK_TRILHA_PERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID_PERFIL)
);

CREATE TABLE ETAPA_TRILHA (
    ID_ETAPA        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_TRILHA       NUMBER NOT NULL,
    ORDEM           NUMBER NOT NULL,
    DESCRICAO       VARCHAR2(500) NOT NULL,
    TIPO_RECURSO    VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_ETAPA_TRILHA FOREIGN KEY (ID_TRILHA) REFERENCES TRILHA_APRENDIZAGEM(ID_TRILHA),
    CONSTRAINT UK_ETAPA_ORDEM UNIQUE (ID_TRILHA, ORDEM)
);

CREATE TABLE ETAPA_SKILL (
    ID_ETAPA_SKILL  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_ETAPA        NUMBER NOT NULL,
    ID_SKILL        NUMBER NOT NULL,
    CONSTRAINT FK_ES_ETAPA FOREIGN KEY (ID_ETAPA) REFERENCES ETAPA_TRILHA(ID_ETAPA),
    CONSTRAINT FK_ES_SKILL FOREIGN KEY (ID_SKILL) REFERENCES SKILL(ID_SKILL),
    CONSTRAINT UK_ETAPA_SKILL UNIQUE (ID_ETAPA, ID_SKILL)
);

CREATE TABLE LOG_AUDITORIA (
    ID_LOG              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME_TABELA         VARCHAR2(50) NOT NULL,
    TIPO_OPERACAO       VARCHAR2(10) NOT NULL,
    DATA_OPERACAO       DATE DEFAULT SYSDATE,
    USUARIO_BD          VARCHAR2(50),
    DADOS_ANTERIORES    CLOB
);

--======================================================================
-- 3. TRIGGERS DE AUDITORIA
--======================================================================

CREATE OR REPLACE TRIGGER TRG_AUDIT_USUARIO
AFTER INSERT OR UPDATE OR DELETE ON USUARIO
FOR EACH ROW
DECLARE
    v_operacao LOG_AUDITORIA.TIPO_OPERACAO%TYPE;
    v_dados_anteriores CLOB;
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
        v_dados_anteriores := NULL;
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        v_dados_anteriores := 'ID: ' || :OLD.ID_USUARIO || ', Nome Antigo: ' || :OLD.NOME || ', Email Antigo: ' || :OLD.EMAIL;
    ELSIF DELETING THEN
        v_operacao := 'DELETE';
        v_dados_anteriores := 'ID: ' || :OLD.ID_USUARIO || ', Nome: ' || :OLD.NOME || ', Email: ' || :OLD.EMAIL;
    END IF;

    INSERT INTO LOG_AUDITORIA (NOME_TABELA, TIPO_OPERACAO, USUARIO_BD, DADOS_ANTERIORES)
    VALUES ('USUARIO', v_operacao, USER, v_dados_anteriores);
END;
/

--======================================================================
-- 4. PACOTE: ESPECIFICAÇÃO (HEADER)
--======================================================================

CREATE OR REPLACE PACKAGE PKG_PERFIS_E_TRILHAS AS
    -- Procedures de Insert (Originais)
    PROCEDURE PR_INSERIR_USUARIO (
        p_nome          IN USUARIO.NOME%TYPE,
        p_email         IN USUARIO.EMAIL%TYPE,
        p_senha_hash    IN USUARIO.SENHA_HASH%TYPE,
        p_id_usuario    OUT USUARIO.ID_USUARIO%TYPE
    );
    PROCEDURE PR_INSERIR_SKILL (
        p_nome_skill    IN SKILL.NOME_SKILL%TYPE,
        p_tipo          IN SKILL.TIPO%TYPE,
        p_id_skill      OUT SKILL.ID_SKILL%TYPE
    );
    PROCEDURE PR_ADICIONAR_SKILL_PERFIL (
        p_id_usuario    IN USUARIO.ID_USUARIO%TYPE,
        p_id_skill      IN SKILL.ID_SKILL%TYPE,
        p_nivel_dominio IN PERFIL_SKILL.NIVEL_DOMINIO%TYPE
    );
    PROCEDURE PR_INSERIR_TRILHA (
        p_id_usuario      IN USUARIO.ID_USUARIO%TYPE,
        p_titulo_objetivo IN TRILHA_APRENDIZAGEM.TITULO_OBJETIVO%TYPE,
        p_id_trilha       OUT TRILHA_APRENDIZAGEM.ID_TRILHA%TYPE
    );
    PROCEDURE PR_INSERIR_ETAPA_TRILHA (
        p_id_trilha     IN TRILHA_APRENDIZAGEM.ID_TRILHA%TYPE,
        p_ordem         IN ETAPA_TRILHA.ORDEM%TYPE,
        p_descricao     IN ETAPA_TRILHA.DESCRICAO%TYPE,
        p_tipo_recurso  IN ETAPA_TRILHA.TIPO_RECURSO%TYPE,
        p_id_etapa      OUT ETAPA_TRILHA.ID_ETAPA%TYPE
    );
    PROCEDURE PR_ADICIONAR_SKILL_ETAPA (
        p_id_etapa    IN ETAPA_TRILHA.ID_ETAPA%TYPE,
        p_id_skill    IN SKILL.ID_SKILL%TYPE
    );

    -- Procedures de CRUD (Novas)
    PROCEDURE PR_ATUALIZAR_TRILHA (
        p_id_trilha       IN TRILHA_APRENDIZAGEM.ID_TRILHA%TYPE,
        p_titulo_objetivo IN TRILHA_APRENDIZAGEM.TITULO_OBJETIVO%TYPE
    );

    PROCEDURE PR_DELETAR_TRILHA (
        p_id_trilha IN TRILHA_APRENDIZAGEM.ID_TRILHA%TYPE
    );

    -- Funções e Exportação
    FUNCTION FN_PERFIL_TO_JSON_MANUAL (p_id_usuario IN USUARIO.ID_USUARIO%TYPE) RETURN CLOB;
    FUNCTION FN_CALC_COMPATIBILIDADE (p_id_perfil IN PERFIL.ID_PERFIL%TYPE, p_titulo_objetivo IN TRILHA_APRENDIZAGEM.TITULO_OBJETIVO%TYPE) RETURN CLOB;
    PROCEDURE PR_EXPORTAR_DATASET_JSON (p_json_dataset OUT CLOB);

END PKG_PERFIS_E_TRILHAS;
/

--======================================================================
-- 5. PACOTE: CORPO (BODY - IMPLEMENTAÇÃO)
--======================================================================

CREATE OR REPLACE PACKAGE BODY PKG_PERFIS_E_TRILHAS AS

    -- 1. Insert Usuario
    PROCEDURE PR_INSERIR_USUARIO (
        p_nome          IN USUARIO.NOME%TYPE,
        p_email         IN USUARIO.EMAIL%TYPE,
        p_senha_hash    IN USUARIO.SENHA_HASH%TYPE,
        p_id_usuario    OUT USUARIO.ID_USUARIO%TYPE
    ) AS
        v_id_perfil PERFIL.ID_PERFIL%TYPE;
    BEGIN
        INSERT INTO USUARIO (NOME, EMAIL, SENHA_HASH) VALUES (p_nome, p_email, p_senha_hash)
        RETURNING ID_USUARIO INTO p_id_usuario;
        INSERT INTO PERFIL (ID_USUARIO, TITULO_CARGO_ATUAL, DATA_ULTIMA_ATUALIZACAO) VALUES (p_id_usuario, 'Indefinido', SYSDATE)
        RETURNING ID_PERFIL INTO v_id_perfil;
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20002, 'Erro ao inserir usuário: ' || SQLERRM);
    END PR_INSERIR_USUARIO;

    -- 2. Insert Skill
    PROCEDURE PR_INSERIR_SKILL (
        p_nome_skill    IN SKILL.NOME_SKILL%TYPE,
        p_tipo          IN SKILL.TIPO%TYPE,
        p_id_skill      OUT SKILL.ID_SKILL%TYPE
    ) AS
    BEGIN
        INSERT INTO SKILL (NOME_SKILL, TIPO) VALUES (p_nome_skill, p_tipo)
        RETURNING ID_SKILL INTO p_id_skill;
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20011, 'Erro ao inserir skill: ' || SQLERRM);
    END PR_INSERIR_SKILL;

    -- 3. Add Skill Perfil
    PROCEDURE PR_ADICIONAR_SKILL_PERFIL (
        p_id_usuario    IN USUARIO.ID_USUARIO%TYPE,
        p_id_skill      IN SKILL.ID_SKILL%TYPE,
        p_nivel_dominio IN PERFIL_SKILL.NIVEL_DOMINIO%TYPE
    ) AS
        v_id_perfil PERFIL.ID_PERFIL%TYPE;
    BEGIN
        SELECT ID_PERFIL INTO v_id_perfil FROM PERFIL WHERE ID_USUARIO = p_id_usuario;
        INSERT INTO PERFIL_SKILL (ID_PERFIL, ID_SKILL, NIVEL_DOMINIO) VALUES (v_id_perfil, p_id_skill, p_nivel_dominio);
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20014, 'Erro ao associar skill: ' || SQLERRM);
    END PR_ADICIONAR_SKILL_PERFIL;

    -- 4. Insert Trilha
    PROCEDURE PR_INSERIR_TRILHA (
        p_id_usuario      IN USUARIO.ID_USUARIO%TYPE,
        p_titulo_objetivo IN TRILHA_APRENDIZAGEM.TITULO_OBJETIVO%TYPE,
        p_id_trilha       OUT TRILHA_APRENDIZAGEM.ID_TRILHA%TYPE
    ) AS
        v_id_perfil PERFIL.ID_PERFIL%TYPE;
    BEGIN
        SELECT ID_PERFIL INTO v_id_perfil FROM PERFIL WHERE ID_USUARIO = p_id_usuario;
        INSERT INTO TRILHA_APRENDIZAGEM (ID_PERFIL, TITULO_OBJETIVO, STATUS) VALUES (v_id_perfil, p_titulo_objetivo, 'PENDENTE')
        RETURNING ID_TRILHA INTO p_id_trilha;
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20016, 'Erro ao criar trilha: ' || SQLERRM);
    END PR_INSERIR_TRILHA;

    -- 5. Insert Etapa
    PROCEDURE PR_INSERIR_ETAPA_TRILHA (
        p_id_trilha     IN TRILHA_APRENDIZAGEM.ID_TRILHA%TYPE,
        p_ordem         IN ETAPA_TRILHA.ORDEM%TYPE,
        p_descricao     IN ETAPA_TRILHA.DESCRICAO%TYPE,
        p_tipo_recurso  IN ETAPA_TRILHA.TIPO_RECURSO%TYPE,
        p_id_etapa      OUT ETAPA_TRILHA.ID_ETAPA%TYPE
    ) AS
    BEGIN
        INSERT INTO ETAPA_TRILHA (ID_TRILHA, ORDEM, DESCRICAO, TIPO_RECURSO) VALUES (p_id_trilha, p_ordem, p_descricao, p_tipo_recurso)
        RETURNING ID_ETAPA INTO p_id_etapa;
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20018, 'Erro ao inserir etapa: ' || SQLERRM);
    END PR_INSERIR_ETAPA_TRILHA;

    -- 6. Add Skill Etapa
    PROCEDURE PR_ADICIONAR_SKILL_ETAPA (p_id_etapa IN ETAPA_TRILHA.ID_ETAPA%TYPE, p_id_skill IN SKILL.ID_SKILL%TYPE) AS
    BEGIN
        INSERT INTO ETAPA_SKILL (ID_ETAPA, ID_SKILL) VALUES (p_id_etapa, p_id_skill);
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20020, 'Erro ao associar skill/etapa: ' || SQLERRM);
    END PR_ADICIONAR_SKILL_ETAPA;

    -- === IMPLEMENTAÇÃO DO UPDATE ===
    PROCEDURE PR_ATUALIZAR_TRILHA (
        p_id_trilha       IN TRILHA_APRENDIZAGEM.ID_TRILHA%TYPE,
        p_titulo_objetivo IN TRILHA_APRENDIZAGEM.TITULO_OBJETIVO%TYPE
    ) AS
    BEGIN
        UPDATE TRILHA_APRENDIZAGEM
        SET TITULO_OBJETIVO = p_titulo_objetivo
        WHERE ID_TRILHA = p_id_trilha;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20025, 'Trilha não encontrada para atualização.');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20022, 'Erro ao atualizar trilha: ' || SQLERRM);
    END PR_ATUALIZAR_TRILHA;

    -- === IMPLEMENTAÇÃO DO DELETE (COM CASCADE MANUAL) ===
    PROCEDURE PR_DELETAR_TRILHA (
        p_id_trilha IN TRILHA_APRENDIZAGEM.ID_TRILHA%TYPE
    ) AS
    BEGIN
        -- Remove dependências em Etapa_Skill
        DELETE FROM ETAPA_SKILL WHERE ID_ETAPA IN (SELECT ID_ETAPA FROM ETAPA_TRILHA WHERE ID_TRILHA = p_id_trilha);
        -- Remove Etapas
        DELETE FROM ETAPA_TRILHA WHERE ID_TRILHA = p_id_trilha;
        -- Remove a Trilha
        DELETE FROM TRILHA_APRENDIZAGEM WHERE ID_TRILHA = p_id_trilha;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20026, 'Trilha não encontrada para exclusão.');
        END IF;
    EXCEPTION
        WHEN OTHERS THEN RAISE_APPLICATION_ERROR(-20024, 'Erro ao deletar trilha: ' || SQLERRM);
    END PR_DELETAR_TRILHA;


    -- 7. Função JSON Manual
    FUNCTION FN_PERFIL_TO_JSON_MANUAL (p_id_usuario IN USUARIO.ID_USUARIO%TYPE) RETURN CLOB AS
        v_json_result CLOB; v_nome USUARIO.NOME%TYPE; v_cargo PERFIL.TITULO_CARGO_ATUAL%TYPE;
        CURSOR c_skills IS SELECT s.NOME_SKILL, ps.NIVEL_DOMINIO FROM SKILL s JOIN PERFIL_SKILL ps ON s.ID_SKILL = ps.ID_SKILL JOIN PERFIL p ON ps.ID_PERFIL = p.ID_PERFIL WHERE p.ID_USUARIO = p_id_usuario;
        v_skill_array VARCHAR2(32767) := '['; v_count_skills NUMBER := 0;
    BEGIN
        SELECT u.NOME, p.TITULO_CARGO_ATUAL INTO v_nome, v_cargo FROM USUARIO u JOIN PERFIL p ON u.ID_USUARIO = p.ID_USUARIO WHERE u.ID_USUARIO = p_id_usuario;
        FOR r_skill IN c_skills LOOP
            IF v_count_skills > 0 THEN v_skill_array := v_skill_array || ','; END IF;
            v_skill_array := v_skill_array || '{"nome": "' || REPLACE(r_skill.NOME_SKILL, '"', '\"') || '", "nivel": ' || r_skill.NIVEL_DOMINIO || '}';
            v_count_skills := v_count_skills + 1;
        END LOOP;
        v_skill_array := v_skill_array || ']';
        v_json_result := '{"perfil": {"id": ' || p_id_usuario || ', "nome": "' || v_nome || '", "cargo": "' || NVL(v_cargo,'') || '"}, "skills": ' || v_skill_array || '}';
        RETURN v_json_result;
    EXCEPTION WHEN OTHERS THEN RETURN '{}';
    END FN_PERFIL_TO_JSON_MANUAL;

    -- 8. Função Cálculo Compatibilidade
    FUNCTION FN_CALC_COMPATIBILIDADE (p_id_perfil IN PERFIL.ID_PERFIL%TYPE, p_titulo_objetivo IN TRILHA_APRENDIZAGEM.TITULO_OBJETIVO%TYPE) RETURN CLOB AS
        v_email_usuario USUARIO.EMAIL%TYPE; v_compatibilidade NUMBER := 0; v_msg_retorno VARCHAR2(200);
        v_matched_count NUMBER := 0; v_total_required NUMBER := 5;
        c_required CONSTANT SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('Kubernetes', 'AWS', 'Python', 'Git', 'Linux');
    BEGIN
        SELECT u.EMAIL INTO v_email_usuario FROM USUARIO u JOIN PERFIL p ON u.ID_USUARIO = p.ID_USUARIO WHERE p.ID_PERFIL = p_id_perfil;
        IF NOT REGEXP_LIKE(v_email_usuario, '^[a-zA-Z0-9._%+-]+@.+\.(com|org|net)$') THEN RAISE_APPLICATION_ERROR(-20006, 'Email inválido'); END IF;
        FOR i IN 1..v_total_required LOOP
            BEGIN
                SELECT 1 INTO v_matched_count FROM PERFIL_SKILL ps JOIN SKILL s ON ps.ID_SKILL = s.ID_SKILL WHERE ps.ID_PERFIL = p_id_perfil AND s.NOME_SKILL = c_required(i) AND ps.NIVEL_DOMINIO >= 3 AND ROWNUM = 1;
                v_compatibilidade := v_compatibilidade + (100/v_total_required);
            EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
            END;
        END LOOP;
        RETURN '{"objetivo": "' || p_titulo_objetivo || '", "compatibilidade": ' || ROUND(v_compatibilidade) || '}';
    EXCEPTION WHEN OTHERS THEN RETURN '{"erro": "Erro no calculo"}';
    END FN_CALC_COMPATIBILIDADE;

    -- 9. PROCEDURE DE EXPORTAÇÃO PARA MONGODB
    PROCEDURE PR_EXPORTAR_DATASET_JSON (p_json_dataset OUT CLOB) AS
        v_json CLOB := '[';
        v_first_user BOOLEAN := TRUE;
        v_first_skill BOOLEAN;
        v_first_trilha BOOLEAN;

        CURSOR c_users IS SELECT U.ID_USUARIO, U.NOME, U.EMAIL, P.ID_PERFIL, P.TITULO_CARGO_ATUAL FROM USUARIO U JOIN PERFIL P ON U.ID_USUARIO = P.ID_USUARIO;
        CURSOR c_skills (p_perfil_id NUMBER) IS SELECT S.NOME_SKILL, PS.NIVEL_DOMINIO FROM PERFIL_SKILL PS JOIN SKILL S ON PS.ID_SKILL = S.ID_SKILL WHERE PS.ID_PERFIL = p_perfil_id;
        CURSOR c_trilhas (p_perfil_id NUMBER) IS SELECT T.TITULO_OBJETIVO, T.STATUS FROM TRILHA_APRENDIZAGEM T WHERE T.ID_PERFIL = p_perfil_id;
    BEGIN
        FOR r_u IN c_users LOOP
            IF NOT v_first_user THEN v_json := v_json || ','; END IF;
            v_first_user := FALSE;

            v_json := v_json || '{"_id": ' || r_u.ID_USUARIO || ', "nome": "' || r_u.NOME || '", "email": "' || r_u.EMAIL || '", "cargo": "' || r_u.TITULO_CARGO_ATUAL || '"';

            v_json := v_json || ', "habilidades": [';
            v_first_skill := TRUE;
            FOR r_s IN c_skills(r_u.ID_PERFIL) LOOP
                IF NOT v_first_skill THEN v_json := v_json || ','; END IF;
                v_json := v_json || '{"nome": "' || r_s.NOME_SKILL || '", "nivel": ' || r_s.NIVEL_DOMINIO || '}';
                v_first_skill := FALSE;
            END LOOP;
            v_json := v_json || ']';

            v_json := v_json || ', "trilhas": [';
            v_first_trilha := TRUE;
            FOR r_t IN c_trilhas(r_u.ID_PERFIL) LOOP
                IF NOT v_first_trilha THEN v_json := v_json || ','; END IF;
                v_json := v_json || '{"objetivo": "' || r_t.TITULO_OBJETIVO || '", "status": "' || r_t.STATUS || '"}';
                v_first_trilha := FALSE;
            END LOOP;
            v_json := v_json || ']}';

        END LOOP;
        v_json := v_json || ']';
        p_json_dataset := v_json;
    END PR_EXPORTAR_DATASET_JSON;

END PKG_PERFIS_E_TRILHAS;
/

--======================================================================
-- 6. INSERÇÃO DE DADOS (CARGA INICIAL COM SENHA HASH)
--======================================================================
DECLARE
    v_uid NUMBER; v_sid NUMBER; v_tid NUMBER; v_eid NUMBER;
    v_sk_sql NUMBER; v_sk_aws NUMBER; v_sk_docker NUMBER; v_sk_k8s NUMBER;
    -- Hash gerado para a senha "123456" (padrão BCrypt)
    v_senha_padrao VARCHAR2(100) := '$2a$10$eAccYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZqKu';
BEGIN
    -- Carga Skills Básicas
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('SQL', 'HARD', v_sk_sql);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('AWS', 'HARD', v_sk_aws);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Docker', 'HARD', v_sk_docker);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Kubernetes', 'HARD', v_sk_k8s);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Python', 'HARD', v_sid);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Java', 'HARD', v_sid);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Comunicação', 'SOFT', v_sid);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Liderança', 'SOFT', v_sid);
    -- REINSERINDO AS SKILLS QUE FALTAVAM
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Git', 'HARD', v_sid);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('React', 'HARD', v_sid);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Scrum', 'SOFT', v_sid);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Excel', 'HARD', v_sid);
    PKG_PERFIS_E_TRILHAS.PR_INSERIR_SKILL('Inglês', 'SOFT', v_sid);

    -- Carga Usuários (10)
    FOR i IN 1..10 LOOP
        -- Agora usando a senha hash
        PKG_PERFIS_E_TRILHAS.PR_INSERIR_USUARIO('Usuario '||i, 'user'||i||'@empresa.com', v_senha_padrao, v_uid);

        PKG_PERFIS_E_TRILHAS.PR_ADICIONAR_SKILL_PERFIL(v_uid, v_sk_sql, 3);

        IF i < 5 THEN 
             PKG_PERFIS_E_TRILHAS.PR_ADICIONAR_SKILL_PERFIL(v_uid, v_sk_aws, 2);
             PKG_PERFIS_E_TRILHAS.PR_INSERIR_TRILHA(v_uid, 'Engenheiro de DevOps Cloud', v_tid);
             PKG_PERFIS_E_TRILHAS.PR_INSERIR_ETAPA_TRILHA(v_tid, 1, 'Curso Cloud', 'CURSO', v_eid);
        ELSE
             PKG_PERFIS_E_TRILHAS.PR_INSERIR_TRILHA(v_uid, 'Gerente de Projetos', v_tid);
        END IF;
    END LOOP;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Carga de Dados Completa Realizada.');
END;
/

--======================================================================
-- 7. DEMONSTRAÇÃO FINAL (TESTE DAS 3 FUNÇÕES)
--======================================================================
DECLARE
    v_json_dataset CLOB;
    v_json_manual CLOB;
    v_u_demo NUMBER;
    v_p_demo NUMBER;
BEGIN
    -- Seleciona um usuário de teste (Correção da Ambiguidade aqui: U.ID_USUARIO)
    SELECT U.ID_USUARIO, P.ID_PERFIL INTO v_u_demo, v_p_demo 
    FROM USUARIO U JOIN PERFIL P ON U.ID_USUARIO = P.ID_USUARIO 
    WHERE ROWNUM = 1;

    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('1. TESTE FUNÇÃO MANUAL (JSON PERFIL):');
    DBMS_OUTPUT.PUT_LINE(PKG_PERFIS_E_TRILHAS.FN_PERFIL_TO_JSON_MANUAL(v_u_demo));
    
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('2. TESTE FUNÇÃO COMPATIBILIDADE (CÁLCULO):');
    DBMS_OUTPUT.PUT_LINE(PKG_PERFIS_E_TRILHAS.FN_CALC_COMPATIBILIDADE(v_p_demo, 'Engenheiro de DevOps Cloud'));

    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('3. GERANDO DATASET COMPLETO PARA MONGODB (JSON):');
    PKG_PERFIS_E_TRILHAS.PR_EXPORTAR_DATASET_JSON(v_json_dataset);
    DBMS_OUTPUT.PUT_LINE(SUBSTR(v_json_dataset, 1, 2000)); -- Imprime os primeiros 2000 caracteres
    DBMS_OUTPUT.PUT_LINE('... (Dataset continua) ...');
    DBMS_OUTPUT.PUT_LINE('--------------------------------------------------');
END;
/