spring:
  application:
    name: pathfinder-ai

  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm555317
    password: "251004"
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: rm555317

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://seu-identity-provider.com/auth/realms/seu-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

  cache:
    type: caffeine
    cache-names:
      - learning-paths
    caffeine:
      spec: expireAfterWrite=10m,maximumSize=500

  ai:
    openai:
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      api-key: AIzaSyDq-j2_3OKM9xiEasO63FpCYRmdBAf3AF4
      chat:
        options:
          model: gemini-2.0-flash
          temperature: 0.7

messages:
  basename: i18n/messages
  encoding: UTF-8
