package com.fiap.globalsolution.dto.response;

import com.fiap.globalsolution.domain.TrilhaAprendizagem;
import com.fiap.globalsolution.domain.enums.StatusTrilha;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@Schema(description = "DTO for learning path details.")
public class LearningPathDetailResponse {

    @Schema(description = "Unique path ID.", example = "10")
    private Long idTrilha;

    @Schema(description = "User profile ID.", example = "1")
    private Long idPerfil;

    @Schema(description = "Path objective.", example = "Data Engineer")
    private String tituloObjetivo;

    @Schema(description = "Current processing status.", example = "CONCLUIDA")
    private StatusTrilha status;

    @Schema(description = "JSON content generated by the AI.", example = "{\"path\": [{\"title\": \"Introduction\", ...}]}")
    private String dadosJsonIA;

    public LearningPathDetailResponse(TrilhaAprendizagem trilha) {
        this.idTrilha = trilha.getId();
        this.idPerfil = trilha.getPerfil() != null ? trilha.getPerfil().getId() : null;
        this.tituloObjetivo = trilha.getTituloObjetivo();
        this.status = trilha.getStatus();
        this.dadosJsonIA = trilha.getDadosJsonIA();
    }
}