package com.fiap.globalsolution.dto.response;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fiap.globalsolution.domain.TrilhaAprendizagem;
import com.fiap.globalsolution.domain.enums.StatusTrilha;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Data
@NoArgsConstructor
@Slf4j
@Schema(description = "DTO for learning path details.")
public class LearningPathDetailResponse {

    private static final ObjectMapper mapper = new ObjectMapper();

    @Schema(description = "Unique path ID.", example = "10")
    private Long idTrilha;

    @Schema(description = "User profile ID.", example = "1")
    private Long idPerfil;

    @Schema(description = "Path objective.", example = "Data Engineer")
    private String tituloObjetivo;

    @Schema(description = "Current processing status.", example = "CONCLUIDA")
    private StatusTrilha status;

    @Schema(description = "JSON content generated by the AI as an Object.", example = "{\"path\": [{\"title\": \"Introduction\", ...}]}")
    private Object dadosJsonIA;

    public LearningPathDetailResponse(TrilhaAprendizagem trilha) {
        this.idTrilha = trilha.getId();
        this.idPerfil = trilha.getPerfil() != null ? trilha.getPerfil().getId() : null;
        this.tituloObjetivo = trilha.getTituloObjetivo();
        this.status = trilha.getStatus();

        if (trilha.getDadosJsonIA() != null && !trilha.getDadosJsonIA().isEmpty()) {
            try {
                this.dadosJsonIA = mapper.readValue(trilha.getDadosJsonIA(), Object.class);
            } catch (JsonProcessingException e) {
                log.error("Error parsing JSON for Trilha ID " + trilha.getId(), e);
                this.dadosJsonIA = null;
            }
        } else {
            this.dadosJsonIA = null;
        }
    }
}
